### ISSUE TITLE
page fault after upgrading asm! to llvm_asm!

### ISSUE THREAD

**Issue by wyfcyx** [rcore-os/rCore_tutorial#13]
`make run` on master branch, and it panicked with:
```
Exception(StorePageFault) va = 0xffffffffffffffe8 instruction = 0x1acfe
panicked at 'page fault!', src/interrupt.rs:76:5
```
* rust-toolchain = nightly-2020-06-04
* riscv = 21e32ee
In the meanwhile, multicore branch worked normally 15 days ago, but now it failed with page fault too. Given that the only change of it in the last two weeks was the update of riscv crate, so I think there maybe some bugs in it. Actually, I made it work again by rolling back the riscv version to c62af46.

**Comment by jiegec** [comment]
No idea.

**Comment by nappingman** [comment]
problem solve yet ？

**Comment by KiritoHugh** [comment]
same error, same rust-toolchain version, same risv version, and rolling back the riscv version to c62af46 does not work for me.

```
Exception(LoadPageFault) va = 0xffffffff00080000 instruction = 0x1ab1a
panicked at 'page fault!', src/interrupt.rs:76:5
```

**Comment by QQxiaoming** [comment]
> 相同的错误、相同的 rust-toolchain 版本、相同的 risv 版本以及将 riscv 版本回滚到 c62af46 对我不起作用。
> 
> ```
> Exception(LoadPageFault) va = 0xffffffff00080000 instruction = 0x1ab1a
> panicked at 'page fault!', src/interrupt.rs:76:5
> ```
我找到了这个page fault的原因在：
在os/src/memory/memory_set/area.rs:50的
pub fn page_copy(&self, pt: &mut PageTableImpl, src: usize, length: usize)函数内，
page会做4K对齐，则进行数据拷贝时，会导致elf起始数据段为非对齐时这个段数据没有正确的写入，进而直接导致用户进程跑飞引起不可预测的错误。这个位置我进行了修改确认能解决该问题，但鉴于官方好像已经重构了这个项目并且此处代码完全重构了，因此就没有提PR了。
